"plugin.plugin_configuration.search_api_saved_searches_notification.*":
  type: mapping
  label: 'Notification plugin configuration'

plugin.plugin_configuration.search_api_saved_searches_notification.email:
  type: mapping
  mapping:
    registered_choose_mail:
      type: boolean
      label: 'Let registered users choose e-mail address'
    activate:
      type: mapping
      label: 'Activation mail settings'
      mapping:
        send:
          type: boolean
          label: 'Send activation mail'
        title:
          type: string
          label: 'Activation mail title'
        body:
          type: string
          label: 'Activation mail body'
    notification:
      type: mapping
      label: 'Notification mail settings'
      mapping:
        title:
          type: string
          label: 'Notification mail title'
        body:
          type: string
          label: 'Notification mail body'
